<?php
require 'db.inc.php';

$db = mysqli_connect(MYSQL_HOST, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DB) or die('Unable to connect. Check your connection parameters.');

switch ($_POST['action']) {
    case 'Add Character':
        // escape incoming values to protect database
        $alias = mysqli_real_escape_string($db, $_POST['alias']);
        $real_name = mysqli_real_escape_string($db, $_POST['real_name']);
        $address = mysqli_real_escape_string($db, $_POST['address']);
        $city = mysqli_real_escape_string($db, $_POST['city']);
        $state = mysqli_real_escape_string($db, $_POST['state']);
        $zipcode_id = mysqli_real_escape_string($db, $_POST['zipcode_id']);
        $alignment = ($_POST['alignment'] == 'good') ? 'good' : 'evil';
        
        // add character information into database tables
        $query = 'INSERT IGNORE INTO comic_zipcode (zipcode_id, city, state) VALUES ("' . $zipcode_id . '", "' . $city . '", "' . $state . '")';
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        $query = 'INSERT INTO comic_lair (lair_id, zipcode_id, address) VALUES (NULL, "' . $zipcode_id . '", "' . $address . '")';
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        // retrieve new lair_id generated by MySQL
        $lair_id = mysqli_insert_id($db);
        
        $query = 'INSERT INTO comic_character (character_id, alias, real_name, lair_id, alignment) VALUES (NULL, "' . $alias . '", "' . $real_name . '", ' . $lair_id . ', "' . $alignment . '")';
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        // retrieve new character_id generated by MySQL
        $character_id = mysqli_insert_id($db);
        
        if (!empty($_POST['powers'])) {
            $values = array();
            foreach ($_POST['powers'] as $power_id) {
                $values[] = sprintf('(%d, %d)', $character_id, $power_id);
            }
            $query = 'INSERT IGNORE INTO comic_character_power (character_id, power_id) VALUES ' . implode(',', $values);
            mysqli_query($db, $query) or die(mysqli_error($db));
        }
        
        if (!empty($_POST['rivalries'])) {
            $values = array();
            foreach ($_POST['rivalries'] as $rival_id) {
                $values[] = sprintf('(%d, %d)', $character_id, $rival_id);
            }
            // alignment will affect column order
            $columns = ($alignment == 'good') ? '(hero_id, villain_id)' : '(villain_id, hero_id)';
            $query = 'INSERT IGNORE INTO comic_rivalry ' . $columns . ' VALUES ' . implode(',', $values);
            mysqli_query($db, $query) or die(mysqli_error($db));
        }
        
        $redirect = 'list_characters.php';
        break;
        
    case 'Delete Character':
        // make sure character_id is a number just to be safe
        $character_id = (int)$_POST['character_id'];
        
        // delete character information from tables
        $query = 'DELETE FROM c, l USING comic_character c, comic_lair l WHERE c.lair_id = l.lair_id AND c.character_id = ' . $character_id;
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        $query = 'DELETE FROM comic_character_power WHERE character_id = ' . $character_id;
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        $query = 'DELETE FROM comic_rivalry WHERE hero_id = ' . $character_id . ' OR villain_id = ' . $character_id;
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        $redirect = 'list_characters.php';
        break;
        
    case 'Edit Character':
        // escape incoming values to protect database
        $character_id = (int)$_POST['character_id'];
        $alias = mysqli_real_escape_string($db, $_POST['alias']);
        $real_name = mysqli_real_escape_string($db, $_POST['real_name']);
        $address = mysqli_real_escape_string($db, $_POST['address']);
        $city = mysqli_real_escape_string($db, $_POST['city']);
        $state = mysqli_real_escape_string($db, $_POST['state']);
        $zipcode_id = mysqli_real_escape_string($db, $_POST['zipcode_id']);
        $alignment = ($_POST['alignment'] == 'good') ? 'good' : 'evil';
        
        // update existing character information in tables
        $query = 'INSERT IGNORE INTO comic_zipcode (zipcode_id, city, state) VALUES ("' . $zipcode_id . '", "' . $city . '", "' . $state . '")';
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        $query = 'UPDATE comic_lair l, comic_character c SET l.zipcode_id = ' . $zipcode_id . ', l.address = "' . $address . '", c.real_name = "' . $real_name . '", c.alias = "' . $alias . '", c.alignment = "' . $alignment . '" WHERE c.character_id = ' . $character_id . ' AND c.lair_id = l.lair_id';
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        $query = 'DELETE FROM comic_character_power WHERE character_id = ' . $character_id;
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        if (!empty($_POST['powers'])) {
            $values = array();
            foreach ($_POST['powers'] as $power_id) {
                $values[] = sprintf('(%d, %d)', $character_id, $power_id);
            }
            $query = 'INSERT IGNORE INTO comic_character_power (character_id, power_id) VALUES ' . implode(',', $values);
            mysqli_query($db, $query) or die(mysqli_error($db));
        }
        
        $query = 'DELETE FROM comic_rivalry WHERE hero_id = ' . $character_id . ' OR villain_id = ' . $character_id;
        mysqli_query($db, $query) or die(mysqli_error($db));
        
        if (!empty($_POST['rivalries'])) {
            $values = array();
            foreach ($_POST['rivalries'] as $rival_id) {
                $values[] = sprintf('(%d, %d)', $character_id, $rival_id);
            }
            // alignment will affect column order
            $columns = ($alignment == 'good') ? '(hero_id, villain_id)' : '(villain_id, hero_id)';
            $query = 'INSERT IGNORE INTO comic_rivalry ' . $columns . ' VALUES ' . implode(',', $values);
            mysqli_query($db, $query) or die(mysqli_error($db));
        }
        
        $redirect = 'list_characters.php';
        break;
        
    case 'Delete Selected Powers':
        if (!empty($_POST['powers'])) {
            // escape incoming values to protect database-- they should be numeric
            // values, but just to be safe
            $powers = implode(',', $_POST['powers']);
            $powers = mysqli_real_escape_string($db, $powers);
            
            // delete powers
            $query = 'DELETE FROM comic_power WHERE power_id IN (' . $powers . ')';
            mysqli_query($db, $query) or die(mysqli_error($db));
            
            $query = 'DELETE FROM comic_character_power WHERE power_id IN (' . $powers . ')';
            mysqli_query($db, $query) or die(mysqli_error($db));
        }
        
        $redirect = 'edit_power.php';
        break;
        
    case 'Add New Power':
        // trim and check power to prevent adding blank values
        $power = trim($_POST['new_power']);
        if ($power != '') {
            // escape incoming value
            $power = mysqli_real_escape_string($db, $power);
            
            // create new power
            $query = 'INSERT IGNORE INTO comic_power (power_id, power) VALUES (NULL, "' . $power . '")';
            mysqli_query($db, $query) or die(mysqli_error($db));
        }
        
        $redirect = 'edit_power.php';
        break;
        
    default:
        $redirect = 'list_characters.php';
}

header('Location: ' . $redirect);
?>